version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './keys/:/etc/nginx/keys/'
      - '/mnt/data/website:/data'
    networks:
      - objectify-internal-network
networks:
  objectify-internal-network:
