version: '3'
services:
  container:
    container_name: contenter
    image: mirmalis/contenter
    pull_policy: always
    volumes:
      - /mnt/configs/projects/Contenter/data/sqlite:/dbs
      - /mnt/configs/projects/Contenter/data/keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    networks:
      - objectify-internal-network
networks:
  objectify-internal-network:
    name: nginx_objectify-internal-network
    external: true
