FROM mcr.microsoft.com/dotnet/aspnet:8.0.6-bookworm-slim-arm64v8 AS final
WORKDIR /app
# RUN apt-get update && apt-get install -y \
#     sqlite3 \
#     libsqlite3-dev \
#     && rm -rf /var/lib/apt/lists/*
COPY /publish .
ENTRYPOINT ["dotnet", "Contenter.dll"]
